In this notebook, we do some analysis on the distributed reproduction numbers of french school example.

In [46]:
# import packages
import numpy as np
import pandas as pd
import sys
import os
sys.path.append(os.path.join(os.path.dirname("__file__"), ".."))
import matplotlib.pyplot as plt

In [47]:
# load data
df = pd.read_csv("../data/reproduction_number_matrix.csv", header=None)
print(f"The reproduction number has {df.shape[0]} rows and {df.shape[1]} columns.")
df.head()

The reproduction number has 237 rows and 237 columns.

,0,1,2,3,4,5,6,7,8,9,...,227,228,229,230,231,232,233,234,235,236
0,0.000000,0.0,0.000000,0.071178,0.000000,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.097062,0.000000
1,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000
2,0.000000,0.0,0.000000,0.000000,0.071178,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.103532,0.000000,0.000000
3,0.071178,0.0,0.000000,0.000000,0.232948,0.110003,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.161769,0.000000,0.155299
4,0.000000,0.0,0.071178,0.232948,0.000000,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.110003,0.194123,0.440013,0.116474

In [48]:
# convert to numpy array
matrix = df.to_numpy()
matrix_nonzero = matrix[np.nonzero(matrix)]

print(f"The matrix have overall {matrix.reshape(-1).shape[0]} entries!")
print(f"The matrix have overall {matrix_nonzero.shape[0]} non-zero entries!")
print(f"The rate of non-zero entries: {matrix[np.nonzero(matrix)].shape[0] / matrix.reshape(-1).shape[0]}.")

The matrix have overall 56169 entries!
The matrix have overall 3106 non-zero entries!
The rate of non-zero entries: 0.055297406042478944.

In [49]:
# more analysis
print(f"The value of minimal nonzero entry is {np.min(matrix_nonzero)}")
print(f"The value of maximal nonzero entry is {np.max(matrix_nonzero)}")

The value of minimal nonzero entry is 0.064707722810282
The value of maximal nonzero entry is 2.860081348214465